DELETE FROM Toy;
DELETE FROM Child;

DROP TABLE IF EXISTS Toy;
DROP TABLE IF EXISTS Child;

CREATE TABLE Child (
    ChildId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Happy INT NOT NULL
);

CREATE TABLE Toy (
    ToyId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    ChildId INTEGER NOT NULL,
    FOREIGN KEY (ChildId) REFERENCES Child(ChildId)
);