CREATE TABLE Artist(
	ArtistId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name of Artist TEXT NOT NULL
);


CREATE TABLE Song(
	SongId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name of Song TEXT NOT NULL,
	ArtistID INTEGER NOT NULL,
	FOREIGN KEY (ArtistId) REFERENCES Artist(ArtistId)
);


CREATE TABLE Album(
	AlbumId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name of Album TEXT NOT NULL,
	ArtistID INTEGER NOT NULL,
	FOREIGN KEY (ArtistId) REFERENCES Artist(ArtistId)
);


CREATE TABLE Genre(
	GenreId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name of Genre TEXT NOT NULL
);


CREATE TABLE SongAlbum(
	SongAlbumId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SongID INTEGER NOT NULL,
	AlbumID INTEGER NOT NULL,
	FOREIGN KEY (SongId) REFERENCES Song(SongId),
	FOREIGN KEY (AlbumId) REFERENCES Album(AlbumId)
);


CREATE TABLE SongGenre(
	SongGenreId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	SongID INTEGER NOT NULL,
	GenreID INTEGER NOT NULL,
	FOREIGN KEY (SongId) REFERENCES Song(SongId),
	FOREIGN KEY (GenreId) REFERENCES Genre(GenreId)	
);

SELECT * FROM Artist;
SELECT * FROM Song;
SELECT * FROM Album;
SELECT * FROM Genre;
SELECT * FROM SongAlbum;
SELECT * FROM SongGenre;

DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Song;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS SongAlbum;
DROP TABLE IF EXISTS SongGenre;
